
/*CREATE DATABASE IF NOT EXISTS ycc_optesthesia;
CREATE TABLE helmet_cloth_logs(
    log_id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    base_code VARCHAR(63) NOT NULL,
    device_id VARCHAR(63) NOT NULL,
    person TINYINT UNSIGNED NOT NULL,
    no_helmet TINYINT UNSIGNED NOT NULL,
    no_cloth TINYINT UNSIGNED NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    add_nam VARCHAR(63) NOT NULL,
    add_tim DATETIME NOT NULL,
    update_nam VARCHAR(63) NOT NULL,
    update_tim DATETIME NOT NULL
);

CREATE DATABASE IF NOT EXISTS ycc_optesthesia;

USE ycc_optesthesia;*/

CREATE TABLE IF NOT EXISTS helmet_cloth_logs (
    log_id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    base_code VARCHAR(63) NOT NULL,
    device_id VARCHAR(63) NOT NULL,
    person TINYINT UNSIGNED NOT NULL,
    no_helmet TINYINT UNSIGNED NOT NULL,
    no_cloth TINYINT UNSIGNED NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    add_nam VARCHAR(63) NOT NULL,
    add_tim DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_nam VARCHAR(63) NOT NULL,
    update_tim DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
